CREATE DATABASE IF NOT EXISTS FROSTY_APP;
CREATE SCHEMA IF NOT EXISTS FROSTY_APP.CORE;
CREATE OR REPLACE TABLE FROSTY_APP.CORE.FIREY_FRIDAY (ID INT, CHALLENGE VARCHAR, TOPIC VARCHAR);
INSERT INTO FROSTY_APP.CORE.FIREY_FRIDAY (ID, CHALLENGE, TOPIC) VALUES
(1, 'Challenge 1', 'Arrays'),
(2, 'Challenge 2', 'Sorting Algorithms'),
(3, 'Challenge 3', 'Linked Lists'),
(4, 'Challenge 4', 'Stacks and Queues'),
(5, 'Challenge 5', 'Arrays'),
(6, 'Challenge 6', 'Graphs'),
(7, 'Challenge 7', 'Recursion'),
(8, 'Challenge 8', 'Dynamic Programming'),
(9, 'Challenge 9', 'Arrays'),
(10, 'Challenge 10', 'Bit Manipulation'),
(11, 'Challenge 11', 'String Manipulation'),
(12, 'Challenge 12', 'Graphs'),
(13, 'Challenge 13', 'Greedy Algorithms'),
(14, 'Challenge 14', 'Object-Oriented Programming'),
(15, 'Challenge 15', 'Arrays'),
(16, 'Challenge 16', 'Concurrency and Multithreading'),
(17, 'Challenge 17', 'Error Handling and Debugging'),
(18, 'Challenge 18', 'Design Patterns'),
(19, 'Challenge 19', 'Arrays'),
(20, 'Challenge 20', 'SQL Queries'),
(21, 'Challenge 21', 'RESTful APIs'),
(22, 'Challenge 22', 'Dynamic Programming'),
(23, 'Challenge 23', 'Containerization and Virtualization'),
(24, 'Challenge 24', 'CI/CD'),
(25, 'Challenge 25', 'Automated Testing'),
(26, 'Challenge 26', 'Web Security'),
(27, 'Challenge 27', 'Arrays'),
(28, 'Challenge 28', 'Networking Basics'),
(29, 'Challenge 29', 'Cloud Computing'),
(30, 'Challenge 30', 'Arrays'),
(31, 'Challenge 31', 'RESTful APIs'),
(32, 'Challenge 32', 'SQL Queries'),
(33, 'Challenge 33', 'Sorting Algorithms'),
(34, 'Challenge 34', 'Bit Manipulation'),
(35, 'Challenge 35', 'Graphs'),
(36, 'Challenge 36', 'Object-Oriented Programming'),
(37, 'Challenge 37', 'String Manipulation'),
(38, 'Challenge 38', 'Concurrency and Multithreading'),
(39, 'Challenge 39', 'Design Patterns'),
(40, 'Challenge 40', 'Error Handling and Debugging'),
(41, 'Challenge 41', 'CI/CD'),
(42, 'Challenge 42', 'Automated Testing'),
(43, 'Challenge 43', 'Web Security'),
(44, 'Challenge 44', 'Arrays'),
(45, 'Challenge 45', 'Networking Basics'),
(46, 'Challenge 46', 'Cloud Computing'),
(47, 'Challenge 47', 'Containerization and Virtualization'),
(48, 'Challenge 48', 'RESTful APIs'),
(49, 'Challenge 49', 'Dynamic Programming'),
(50, 'Challenge 50', 'SQL Queries');